#!/bin/bash

PROGNAME=$(basename "$0")
state=$1
actions=$2

function log {
    logger - i -t "$PROGNAME" "$*"
}

log "Running $action $state"
if [[ $state == post ]]; then
    modprobe -r 8821ce && modprobe -i 8821ce 
fi

: '
Resume Wi-Fi after suspend
===========================
dir: /lib/systemd/system-sleep/{fileName}
exe: chmod +x /lib/systemd/system-sleep/{fileName}
src: https://askubuntu.com/questions/1029250/ubuntu-18-04-ethernet-disconnected-after-suspend
verify: grep {fileName} /var/log/syslog
'
