#!/bin/bash

PROGNAME=$(basename "$0")
state=$1
actions=$2

function log {
    logger - i -t "$PROGNAME" "$*"
}

log "Running $action $state"
if [[ $state == post ]]; then
    modprobe -r 8821ce && modprobe -i 8821ce 
fi
