: '
Wifi is connected but there is no internet, DNS might not be set properly
'

pushd . && cd /etc/
echo "Removing old resolv.conf..."
rm -rf resolv.conf
sleep 1
echo "Creating new resolv.conf..."
cat << EOF > ./resolv.conf
# Generated by zaj-e SetUpDNS script
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF
sleep 1
popd
echo "Finished Successfully"
